# SPDX-FileCopyrightText: 2024-2025 Soulfind Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build
on: [push, pull_request, workflow_dispatch]
permissions: {}

jobs:
  build:
    timeout-minutes: 15
    strategy:
      matrix:
        os: [linux-x86_64, linux-arm64, freebsd-x86_64, openbsd-x86_64, macos-x86_64, macos-arm64,
             windows-x86_64, windows-arm64]
        compiler: [ldc, dmd, gdc]
        include:
          - compiler: ldc
            package: ldc

          - compiler: dmd
            package: dmd

          - compiler: gdc
            package: gcc-gdc

          - os: linux-x86_64
            image: ubuntu-latest
            container: alpine:edge

          - os: linux-arm64
            image: ubuntu-24.04-arm
            container: alpine:edge

          - os: freebsd-x86_64
            image: ubuntu-latest
            vm_os: freebsd
            vm_version: '15.0'

          - os: openbsd-x86_64
            image: ubuntu-latest
            vm_os: openbsd
            vm_version: '7.7'

          - os: macos-x86_64
            image: macos-latest
            target: -ax86_64-apple-macos10.12

          - os: macos-arm64
            image: macos-latest
            target: -aarm64-apple-macos11

          - os: windows-x86_64
            image: windows-latest

          - os: windows-arm64
            image: windows-latest

        exclude:
          - os: linux-arm64
            compiler: dmd

          - os: freebsd-x86_64
            compiler: dmd

          - os: freebsd-x86_64
            compiler: gdc

          - os: openbsd-x86_64
            compiler: ldc

          - os: openbsd-x86_64
            compiler: gdc

          - os: macos-x86_64
            compiler: dmd

          - os: macos-x86_64
            compiler: gdc

          - os: macos-arm64
            compiler: dmd

          - os: macos-arm64
            compiler: gdc

          - os: windows-x86_64
            compiler: gdc

          - os: windows-arm64
            compiler: dmd

          - os: windows-arm64
            compiler: gdc
    runs-on: ${{ matrix.image }}
    container:
      image: ${{ matrix.container }}
      volumes:
        - ${{ matrix.container == 'alpine:edge' && '/opt:/opt:rw,rshared' || ' ' }}
        - ${{ matrix.container == 'alpine:edge' && '/opt:/__e/node24:ro,rshared' || ' ' }}
    steps:
      # Workaround from https://github.com/actions/runner/issues/801#issuecomment-2976165281
      - name: Patch native Alpine NodeJS into Runner environment
        if: matrix.container == 'alpine:edge'
        run: |
          sed -i "/^ID=/s/alpine/NotpineForGHA/" /etc/os-release
          apk add nodejs --update-cache
          mkdir /opt/bin
          ln -s /usr/bin/node /opt/bin/node

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up VM (BSD)
        if: startsWith(matrix.os, 'freebsd') || startsWith(matrix.os, 'openbsd')
        uses: cross-platform-actions/action@be3d7e9ff5c8770b9c51b1a8c8c5446e1cad7cf9 # v1.2.0
        with:
          operating_system: ${{ matrix.vm_os }}
          version: ${{ matrix.vm_version }}

      - name: Set up D (Linux)
        if: matrix.container == 'alpine:edge'
        run: apk add ${{ matrix.package }} dub gcc llvm-dev musl-dev sqlite-static zlib-static

      - name: Set up D (FreeBSD)
        if: startsWith(matrix.os, 'freebsd')
        shell: cpa.sh {0}
        run: sudo pkg install -y ${{ matrix.package }} dub sqlite3

      - name: Set up D (OpenBSD)
        if: startsWith(matrix.os, 'openbsd')
        shell: cpa.sh {0}
        run: sudo pkg_add ${{ matrix.package }} dub sqlite3

      - name: Set up D (macOS & Windows)
        if: runner.os == 'macOS' || runner.os == 'Windows'
        uses: dlang-community/setup-dlang@0a7469b93f791d83f30932c6fd105796c6966e20 # v2.0.0
        with:
          compiler: ${{ matrix.compiler }}

      - name: Build (BSD)
        if: startsWith(matrix.os, 'freebsd') || startsWith(matrix.os, 'openbsd')
        shell: cpa.sh {0}
        run: |
          dub build -v --build=release-debug --config=release
          dub test

      - name: Build (Windows arm64)
        if: matrix.os == 'windows-arm64'
        run: |
          $vsPath = vswhere -property installationPath
          cmd /c "`"$vsPath\Common7\Tools\VsDevCmd.bat`" -arch=arm64 -host_arch=x64 && dub build -v --build=release-debug --config=release --arch=aarch64-windows-msvc" && dub test

      - name: Build (Other)
        if: startsWith(matrix.os, 'linux') || startsWith(matrix.os, 'macos') || matrix.os == 'windows-x86_64'
        run: |
          dub build -v --build=release-debug --config=release ${{ matrix.target }}
          dub test ${{ matrix.target }}

      - name: Sign binaries (macOS)
        if: runner.os == 'macOS'
        run: codesign -s - bin/*

      - name: Archive artifacts
        if: matrix.compiler == 'ldc' || (startsWith(matrix.os, 'openbsd') && matrix.compiler == 'dmd')
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: soulfind-${{ matrix.os }}
          path: |
            bin
            !bin/*test*

  attestation:
    if: github.repository == 'soulfind-dev/soulfind' && github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-slim
    timeout-minutes: 15
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist/
          skip-decompress: true

      - name: Attest
        uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6 # v4.2.0
        with:
          subject-path: dist/

  release:
    if: github.repository == 'soulfind-dev/soulfind' && github.ref == 'refs/heads/master'
    needs: attestation
    runs-on: ubuntu-slim
    timeout-minutes: 15
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ github.token }}
      TAG_NAME: latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist/
          skip-decompress: true

      - name: Create release
        run: |
          gh release delete "$TAG_NAME" --cleanup-tag || true
          gh release create "$TAG_NAME" --title "$TAG_NAME" dist/**/*.zip
