# SPDX-FileCopyrightText: 2024-2025 Soulfind Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build
on: [push, pull_request, workflow_dispatch]
permissions: {}

jobs:
  build:
    timeout-minutes: 15
    strategy:
      matrix:
        os: [linux-x86_64, linux-arm64, freebsd-x86_64, macos-x86_64, macos-arm64,
             windows-x86_64, windows-arm64]
        compiler: [ldc, dmd, gdc]
        include:
          - compiler: ldc
            package: ldc

          - compiler: dmd
            package: dmd

          - compiler: gdc
            package: gcc-gdc

          - os: linux-x86_64
            image: ubuntu-latest
            container: alpine:edge

          - os: linux-arm64
            image: ubuntu-24.04-arm
            container: alpine:edge

          - os: freebsd-x86_64
            image: ubuntu-latest

          - os: macos-x86_64
            image: macos-latest
            target: -ax86_64-apple-macos10.12

          - os: macos-arm64
            image: macos-latest
            target: -aarm64-apple-macos11

          - os: windows-x86_64
            image: windows-latest

          - os: windows-arm64
            image: windows-latest

        exclude:
          - os: linux-x86_64
            compiler: dmd

          - os: linux-arm64
            compiler: dmd

          - os: freebsd-x86_64
            compiler: dmd

          - os: freebsd-x86_64
            compiler: gdc

          - os: macos-x86_64
            compiler: dmd

          - os: macos-x86_64
            compiler: gdc

          - os: macos-arm64
            compiler: dmd

          - os: macos-arm64
            compiler: gdc

          - os: windows-x86_64
            compiler: gdc

          - os: windows-arm64
            compiler: dmd

          - os: windows-arm64
            compiler: gdc
    runs-on: ${{ matrix.image }}
    container:
      image: ${{ matrix.container }}
      volumes:
        - ${{ matrix.container == 'alpine:edge' && '/opt:/opt:rw,rshared' || ' ' }}
        - ${{ matrix.container == 'alpine:edge' && '/opt:/__e/node24:ro,rshared' || ' ' }}
    steps:
      # Workaround from https://github.com/actions/runner/issues/801#issuecomment-2976165281
      - name: Patch native Alpine NodeJS into Runner environment
        if: matrix.container == 'alpine:edge'
        run: |
          sed -i "/^ID=/s/alpine/NotpineForGHA/" /etc/os-release
          apk add nodejs --update-cache
          mkdir /opt/bin
          ln -s /usr/bin/node /opt/bin/node

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up D (Alpine Linux)
        if: matrix.container == 'alpine:edge'
        run: apk add ${{ matrix.package }} dub gcc musl-dev sqlite-static

      - name: Set up D (macOS & Windows)
        if: runner.os == 'macOS' || runner.os == 'Windows'
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.compiler }}

      - name: Build (FreeBSD)
        if: matrix.os == 'freebsd-x86_64'
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: freebsd
          version: '15.0'
          run: |
            sudo pkg install -y ${{ matrix.package }} dub sqlite3
            dub build -v --build=release-debug --config=release
            dub test

      - name: Build (Windows arm64)
        if: matrix.os == 'windows-arm64'
        run: |
          $vsPath = vswhere -property installationPath
          cmd /c "`"$vsPath\Common7\Tools\VsDevCmd.bat`" -arch=arm64 -host_arch=x64 && dub build -v --build=release-debug --config=release --arch=aarch64-windows-msvc" && dub test

      - name: Build (Other)
        if: matrix.os != 'freebsd-x86_64' && matrix.os != 'windows-arm64'
        run: |
          dub build -v --build=release-debug --config=release ${{ matrix.target }}
          dub test ${{ matrix.target }}

      - name: Sign binaries (macOS)
        if: runner.os == 'macOS'
        run: codesign -s - bin/*

      - name: Archive artifacts
        if: matrix.compiler == 'ldc'
        uses: actions/upload-artifact@v7
        with:
          name: soulfind-${{ matrix.os }}
          path: |
            bin
            !bin/*test*

  release:
    needs: build
    if: github.repository == 'soulfind-dev/soulfind' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ github.token }}
      TAG_NAME: latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: dist/
          skip-decompress: true

      - name: Create release
        run: |
          gh release delete "$TAG_NAME" --cleanup-tag || true
          gh release create "$TAG_NAME" --title "$TAG_NAME" dist/**/*.zip
