# SPDX-FileCopyrightText: 2025 Soulfind Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: Container
on: [push, pull_request]
permissions: {}
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    timeout-minutes: 15
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            image: ubuntu-latest

          - arch: arm64
            image: ubuntu-24.04-arm
    runs-on: ${{ matrix.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build image
        run: docker build -t "$IMAGE_NAME:latest-${{ matrix.arch }}" .

      - name: Save image
        run: |
          docker save -o soulfind-image-${{ matrix.arch }}.tar \
            "$IMAGE_NAME:latest-${{ matrix.arch }}"

      - name: Upload image artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: soulfind-image-${{ matrix.arch }}
          path: soulfind-image-${{ matrix.arch }}.tar

  publish:
    if: github.repository == 'soulfind-dev/soulfind' && github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      attestations: write
      packages: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          merge-multiple: true

      - name: Load images
        run: |
          docker load --input soulfind-image-amd64.tar
          docker load --input soulfind-image-arm64.tar

      - name: Authentication
        run: echo "${{ github.token }}" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin

      - name: Publish images
        run: |
          docker push "$IMAGE_NAME:latest-amd64"
          docker push "$IMAGE_NAME:latest-arm64"

          docker buildx imagetools create \
            --tag "$IMAGE_NAME:latest" \
            "$IMAGE_NAME:latest-amd64" \
            "$IMAGE_NAME:latest-arm64"

      - name: Load image digests
        run: |
          echo "IMAGE_AMD64_SHA=$(
            docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE_NAME:latest-amd64" |
            cut -d'@' -f2
          )" >> "$GITHUB_ENV"

          echo "IMAGE_ARM64_SHA=$(
            docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE_NAME:latest-arm64" |
            cut -d'@' -f2
          )" >> "$GITHUB_ENV"

      - name: Attest amd64 image
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-name: ${{ env.IMAGE_NAME }}
          subject-digest: ${{ env.IMAGE_AMD64_SHA }}

      - name: Attest arm64 image
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-name: ${{ env.IMAGE_NAME }}
          subject-digest: ${{ env.IMAGE_ARM64_SHA }}
