# SPDX-FileCopyrightText: 2024-2025 Soulfind Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: Lint
on: [push, pull_request]
permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up D
        uses: dlang-community/setup-dlang@0a7469b93f791d83f30932c6fd105796c6966e20 # v2.0.0

      - name: Lint code
        run: dub lint
